---
output:  
  html_document:  
    keep_md: true  
params:
  dtype: details
  ptitle: TRUE
  pbackground: TRUE
  number: 2
  casename: "cs-02"
---

```{r child="case_details_format.Rmd"}

```


### Plots


```{r code1, eval=TRUE,echo=FALSE, fig.width=15}
library(gapminder)
library(dplyr)
library(ggplot2)

gapminder <- gapminder %>% filter(country != "Kuwait")
gapminder.continent <- gapminder %>% 
                          group_by(continent, year) %>% 
                          summarise(gdpPercap = weighted.mean(x = gdpPercap, w = pop), 
                                    pop = sum(as.numeric(pop)))

ggplot(data = gapminder, aes(color = continent, x = lifeExp, y = gdpPercap)) + 
  geom_point(aes(size = pop/100000)) + 
  facet_wrap(~year, nrow = 1) + 
  scale_y_continuous(trans = "sqrt") +
  theme_bw() + labs(x = "Life Expectancy", y = "GDP per capita", size = "Population (100k)", color = "continent")

ggplot(data = gapminder, aes(color = continent, x = year, y = gdpPercap)) + 
  geom_point(aes(size = pop/100000)) + 
  geom_line(aes(group = country)) +
  geom_point(data = gapminder.continent, color = "black", aes(size = pop/100000)) +
  geom_line(data = gapminder.continent, color = "black") +
  facet_wrap(~continent, nrow = 1) +
  theme_bw() + labs(x = "Year", y = "GDP per capita", color = "Continent", size = "Population (100k)")
    


```


