---
title: "R Language Background"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Language

Beyond being **FREE** and the predominate statistical software used in science, industry, research, and business, it has great pedagogical advantages. Daniel Kaplan summarized a great learning/teaching advantage of using R in the following quote.
   
> In mathematics and statistics, the output of one computation often becomes the input to another computation. That's why math courses spend so much time talking about functions (and "domain" and "range", etc.). In word processing, whenever you highlight a word and move it or change the font or replace it, you still end up with stuff on which you can perform the same operations: highlighting, moving, font-changing, etc. Not so in math and statistics. The sorts of operations that you will often perform - solving, integration, statistical summaries, etc. - produce a new kind of thing on which you will be performing new kinds of operations. **In mathematics and statistics, you create a chain of operations and you need to be able to express the steps in that chain. It's not a question of having enough buttons to list all the operations, you'll need combinations of operations - more than could possibly be listed in a menu system.**[^1]

For those of you coming from a computer science background, John D. Cook provides some useful insight[^2]

> I have written software professionally in perhaps a dozen programming languages, and the hardest language for me to learn has been R. The language is actually fairly simple, but it is unconventional.

We can also track the competition between `R` and `Python` [here](https://github.com/hadley/r-python).

For those of you coming from a business or engineering background, you should know that the difficulty of coding in Excel has contributed to some serious blunders in globally impactful discussions [[1](http://www.bloomberg.com/news/articles/2013-04-18/faq-reinhart-rogoff-and-the-excel-error-that-changed-history){target="blank"},[2](http://krugman.blogs.nytimes.com/2013/04/16/holy-coding-error-batman/){target="blank"},[3](http://rooseveltinstitute.org/researchers-finally-replicated-reinhart-rogoff-and-there-are-serious-problems/){target="blank"}] and has [serious flaws](https://datapub.cdlib.org/2014/04/10/abandon-all-hope-ye-who-enter-dates-in-excel/){target="blank"} in how data are even handled.

Below are some references from reputable online sources about the impact and usefulness of R.

* [Fast Company Article on R](http://www.fastcompany.com/3030063/why-the-r-programming-language-is-good-for-business){target="blank"}
    * "R can do literally everything, and all new research is done in R. So especially for businesses that really want to out-compete their competitors on the basis of advanced analytics, they can get access to everything they need within R, things that might not come for five or 10 years through commercial software," says Smith.
* [New York Times on R](http://www.nytimes.com/2009/01/07/technology/business-computing/07program.html?pagewanted=all){target="blank"}
    * "The great beauty of R is that you can modify it to do all sorts of things," said Hal Varian, chief economist at Google. "And you have a lot of prepackaged stuff that's already available, so you're standing on the shoulders of giants."
* [InfoWorld](http://www.infoworld.com/article/2940864/application-development/r-programming-language-statistical-data-analysis.html){target="blank"}
    * Still, Adams and Peng both see R as an accessible language. "I don't come from a computer science background and never had aspirations of becoming a programmer. Knowledge of programming fundamentals certainly helps when adding R to your toolbox, but I wouldn't say it's required to get started," Adams says.
    * "I wouldn't even say R is for programmers. It's best suited for people that have data-oriented problems they're trying to solve, regardless of their programming aptitude."


## Learning R   

We will spend time during class all semester learning new syntax.  During the first two weeks we will spend a little more time learning the basics of R and how to use it (often the most challenging). [Daniel Kaplan's book](http://prep2013.mosaic-web.org/Resources/StartR-kindlepdf-version.pdf) also has a nice introduction.

### Cheat Sheets
* [Base R Language](http://www.rstudio.com/wp-content/uploads/2016/06/r-cheat-sheet.pdf){target="blank"}
* [Advanced R Language](http://www.rstudio.com/wp-content/uploads/2016/02/advancedR.pdf){target="blank"}
* [Advanced Data Visualization](http://www.rstudio.com/wp-content/uploads/2015/12/ggplot2-cheatsheet-2.0.pdf){target="blank"}
* [Data Handling and Programming](https://www.ualberta.ca/~ahamann/teaching/renr690/R_Cheat_Data.pdf){target="blank"}
* [R Reference Card](https://cran.r-project.org/doc/contrib/Short-refcard.pdf){target="blank"}
* [Others](https://www.rstudio.com/resources/cheatsheets/){target="blank"}

## Installing and Introducing R and R-Studio

* [Getting Software Installed](r_help.html)

## R Help and Script Eval

* [RDocumentation](https://www.rdocumentation.org/){target="blank"}


[^1]:  http://prep2013.mosaic-web.org/Resources/StartR-kindlepdf-version.pdf
[^2]: http://www.computerworld.com/article/2497143/business-intelligence/business-intelligence-beginner-s-guide-to-r-introduction.html
